In [31]:
import pandas as pd

In [32]:
# 1.Main Objective

In [33]:
df = pd.read_csv("8_marketing_campaign.csv")

In [34]:
df.head()

,customer_id,age,gender,income_bracket,education,location_type,region,customer_tenure_months,total_purchases,total_spent,...,click_through_rate,previous_campaign_responses,unsubscribe_count,complaint_count,product_category,price_sensitivity,brand_loyalty_score,tech_adoption,days_since_last_campaign,responded
0,CUST_00000001,45,Female,$30k-$60k,High School,Suburban,West,180,13,2645.83,...,NaN,4,1,0,Home,Low,6,Late Adopter,14,No
1,CUST_00000002,25,Female,$100k+,Bachelor,Suburban,Southwest,8,19,1105.91,...,13.8,1,0,0,Fashion,Medium,6,Early Adopter,7,No
2,CUST_00000003,51,Male,$60k-$100k,Bachelor,Suburban,West,1,8,7454.98,...,8.2,8,0,0,Fashion,Medium,5,Mainstream,1,No
3,CUST_00000004,28,Male,$100k+,Graduate,Suburban,Midwest,108,7,2408.26,...,12.1,2,0,0,Sports,Low,6,Early Adopter,3,No
4,CUST_00000005,39,Female,$30k-$60k,Bachelor,Suburban,West,24,13,3952.23,...,10.5,2,0,0,Beauty,Medium,6,Late Adopter,14,No

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 31 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   customer_id                  15000 non-null  str
 1   age                          15000 non-null  int64
 2   gender                       15000 non-null  str
 3   income_bracket               15000 non-null  str
 4   education                    15000 non-null  str
 5   location_type                15000 non-null  str
 6   region                       15000 non-null  str
 7   customer_tenure_months       15000 non-null  int64
 8   total_purchases              15000 non-null  int64
 9   total_spent                  15000 non-null  float64
 10  avg_order_value              14400 non-null  float64
 11  last_purchase_days_ago       15000 non-null  int64
 12  preferred_channel            15000 non-null  str
 13  loyalty_tier                 15000 non-null  str
 14  campaign_type                15000 non-null  str
 15  campaign_category            15000 non-null  str
 16  discount_offered             15000 non-null  int64
 17  campaign_day_of_week         15000 non-null  str
 18  campaign_hour                15000 non-null  str
 19  personalization_level        11236 non-null  str
 20  email_open_rate              14400 non-null  float64
 21  click_through_rate           14400 non-null  float64
 22  previous_campaign_responses  15000 non-null  int64
 23  unsubscribe_count            15000 non-null  int64
 24  complaint_count              15000 non-null  int64
 25  product_category             15000 non-null  str
 26  price_sensitivity            15000 non-null  str
 27  brand_loyalty_score          15000 non-null  int64
 28  tech_adoption                15000 non-null  str
 29  days_since_last_campaign     15000 non-null  int64
 30  responded                    15000 non-null  str
dtypes: float64(4), int64(10), str(17)
memory usage: 3.5 MB

In [36]:
df.describe()

,age,customer_tenure_months,total_purchases,total_spent,avg_order_value,last_purchase_days_ago,discount_offered,email_open_rate,click_through_rate,previous_campaign_responses,unsubscribe_count,complaint_count,brand_loyalty_score,days_since_last_campaign
count,15000.000000,15000.000000,15000.000000,15000.000000,14400.000000,15000.000000,15000.000000,14400.000000,14400.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,41.895200,35.166000,12.004133,2459.183442,205.024741,59.025067,15.804333,37.337569,9.334701,2.996133,0.299733,0.100333,5.979933,29.700000
std,13.432586,34.944109,3.477986,2450.870663,223.674310,59.441630,10.873941,16.012215,5.348901,1.724195,0.544591,0.314335,1.964634,29.736064
min,18.000000,1.000000,1.000000,0.780000,0.060000,1.000000,0.000000,0.700000,0.100000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,32.000000,10.000000,10.000000,703.035000,55.150000,16.000000,10.000000,25.275000,5.300000,2.000000,0.000000,0.000000,5.000000,8.000000
50%,42.000000,24.000000,12.000000,1710.095000,134.655000,40.000000,15.000000,36.300000,8.300000,3.000000,0.000000,0.000000,6.000000,21.000000
75%,51.000000,50.000000,14.000000,3425.717500,280.332500,82.000000,20.000000,48.500000,12.300000,4.000000,1.000000,0.000000,7.000000,41.000000
max,80.000000,180.000000,27.000000,25527.840000,2482.480000,496.000000,50.000000,93.700000,33.800000,13.000000,4.000000,3.000000,10.000000,180.000000

In [37]:
# 2.Data Cleaning

<!-- Total NULL Values  -->

In [38]:
print(df.isnull().sum().sum())

5564

In [39]:
# Null values under each column

In [40]:
print(df.isnull().sum())

customer_id                       0
age                               0
gender                            0
income_bracket                    0
education                         0
location_type                     0
region                            0
customer_tenure_months            0
total_purchases                   0
total_spent                       0
avg_order_value                 600
last_purchase_days_ago            0
preferred_channel                 0
loyalty_tier                      0
campaign_type                     0
campaign_category                 0
discount_offered                  0
campaign_day_of_week              0
campaign_hour                     0
personalization_level          3764
email_open_rate                 600
click_through_rate              600
previous_campaign_responses       0
unsubscribe_count                 0
complaint_count                   0
product_category                  0
price_sensitivity                 0
brand_loyalty_score               0
tech_adoption                     0
days_since_last_campaign          0
responded                         0
dtype: int64

In [41]:
print(df.isnull().sum())

customer_id                       0
age                               0
gender                            0
income_bracket                    0
education                         0
location_type                     0
region                            0
customer_tenure_months            0
total_purchases                   0
total_spent                       0
avg_order_value                 600
last_purchase_days_ago            0
preferred_channel                 0
loyalty_tier                      0
campaign_type                     0
campaign_category                 0
discount_offered                  0
campaign_day_of_week              0
campaign_hour                     0
personalization_level          3764
email_open_rate                 600
click_through_rate              600
previous_campaign_responses       0
unsubscribe_count                 0
complaint_count                   0
product_category                  0
price_sensitivity                 0
brand_loyalty_score               0
tech_adoption                     0
days_since_last_campaign          0
responded                         0
dtype: int64

In [50]:
df['avg_order_value'] = df['avg_order_value'].ffill() 
# print(df.isnull().sum())

customer_id                       0
age                               0
gender                            0
income_bracket                    0
education                         0
location_type                     0
region                            0
customer_tenure_months            0
total_purchases                   0
total_spent                       0
avg_order_value                   0
last_purchase_days_ago            0
preferred_channel                 0
loyalty_tier                      0
campaign_type                     0
campaign_category                 0
discount_offered                  0
campaign_day_of_week              0
campaign_hour                     0
personalization_level          3764
email_open_rate                 600
click_through_rate              600
previous_campaign_responses       0
unsubscribe_count                 0
complaint_count                   0
product_category                  0
price_sensitivity                 0
brand_loyalty_score               0
tech_adoption                     0
days_since_last_campaign          0
responded                         0
dtype: int64

In [54]:
df['personalization_level'] = df['personalization_level'].ffill()

In [55]:
print(df.isnull().sum())

customer_id                      0
age                              0
gender                           0
income_bracket                   0
education                        0
location_type                    0
region                           0
customer_tenure_months           0
total_purchases                  0
total_spent                      0
avg_order_value                  0
last_purchase_days_ago           0
preferred_channel                0
loyalty_tier                     0
campaign_type                    0
campaign_category                0
discount_offered                 0
campaign_day_of_week             0
campaign_hour                    0
personalization_level            0
email_open_rate                600
click_through_rate             600
previous_campaign_responses      0
unsubscribe_count                0
complaint_count                  0
product_category                 0
price_sensitivity                0
brand_loyalty_score              0
tech_adoption                    0
days_since_last_campaign         0
responded                        0
personaliation_level             0
dtype: int64

In [63]:
df['email_open_rate'] = df['email_open_rate'].ffill()

In [64]:
print(df.isnull().sum())

customer_id                    0
age                            0
gender                         0
income_bracket                 0
education                      0
location_type                  0
region                         0
customer_tenure_months         0
total_purchases                0
total_spent                    0
avg_order_value                0
last_purchase_days_ago         0
preferred_channel              0
loyalty_tier                   0
campaign_type                  0
campaign_category              0
discount_offered               0
campaign_day_of_week           0
campaign_hour                  0
personalization_level          0
email_open_rate                0
click_through_rate             1
previous_campaign_responses    0
unsubscribe_count              0
complaint_count                0
product_category               0
price_sensitivity              0
brand_loyalty_score            0
tech_adoption                  0
days_since_last_campaign       0
responded                      0
personaliation_level           0
click_through_rate             1
dtype: int64

In [66]:
df['click_through_rate'] = df['click_through_rate'].ffill()

In [67]:
print(df.isnull().sum())

customer_id                    0
age                            0
gender                         0
income_bracket                 0
education                      0
location_type                  0
region                         0
customer_tenure_months         0
total_purchases                0
total_spent                    0
avg_order_value                0
last_purchase_days_ago         0
preferred_channel              0
loyalty_tier                   0
campaign_type                  0
campaign_category              0
discount_offered               0
campaign_day_of_week           0
campaign_hour                  0
personalization_level          0
email_open_rate                0
click_through_rate             1
previous_campaign_responses    0
unsubscribe_count              0
complaint_count                0
product_category               0
price_sensitivity              0
brand_loyalty_score            0
tech_adoption                  0
days_since_last_campaign       0
responded                      0
personaliation_level           0
click_through_rate             1
dtype: int64

In [52]:
print(df.duplicated().sum())
# O/P = 0 No duplicated are there

0

In [68]:
print(df[])

         customer_id  age  gender income_bracket    education location_type  \
0      CUST_00000001   45  Female      $30k-$60k  High School      Suburban
1      CUST_00000002   25  Female         $100k+     Bachelor      Suburban
2      CUST_00000003   51    Male     $60k-$100k     Bachelor      Suburban
3      CUST_00000004   28    Male         $100k+     Graduate      Suburban
4      CUST_00000005   39  Female      $30k-$60k     Bachelor      Suburban
...              ...  ...     ...            ...          ...           ...
14995  CUST_00014996   39    Male      $30k-$60k     Bachelor         Urban
14996  CUST_00014997   47  Female     $60k-$100k     Bachelor      Suburban
14997  CUST_00014998   37    Male          <$30k     Bachelor         Urban
14998  CUST_00014999   32    Male     $60k-$100k     Bachelor         Urban
14999  CUST_00015000   56    Male     $60k-$100k  High School      Suburban

          region  customer_tenure_months  total_purchases  total_spent  ...  \
0           West                     180               13      2645.83  ...
1      Southwest                       8               19      1105.91  ...
2           West                       1                8      7454.98  ...
3        Midwest                     108                7      2408.26  ...
4           West                      24               13      3952.23  ...
...          ...                     ...              ...          ...  ...
14995  Northeast                      26               15      2569.71  ...
14996       West                     128                8       422.52  ...
14997  Southeast                     126                6      1099.93  ...
14998  Southwest                       8               12      1758.31  ...
14999       West                      10               12        19.32  ...

       unsubscribe_count  complaint_count product_category price_sensitivity  \
0                      1                0             Home               Low
1                      0                0          Fashion            Medium
2                      0                0          Fashion            Medium
3                      0                0           Sports               Low
4                      0                0           Beauty            Medium
...                  ...              ...              ...               ...
14995                  0                0      Electronics            Medium
14996                  0                0           Beauty              High
14997                  0                0             Home               Low
14998                  0                0          Fashion            Medium
14999                  0                0             Home              High

      brand_loyalty_score  tech_adoption  days_since_last_campaign responded  \
0                       6   Late Adopter                        14        No
1                       6  Early Adopter                         7        No
2                       5     Mainstream                         1        No
3                       6  Early Adopter                         3        No
4                       6   Late Adopter                        14        No
...                   ...            ...                       ...       ...
14995                   6  Early Adopter                         4        No
14996                   4     Mainstream                        39       Yes
14997                   9  Early Adopter                        68       Yes
14998                   4     Mainstream                        14       Yes
14999                   5  Early Adopter                         9        No

      personaliation_level click_through_rate
0                    Basic                 NaN
1                 Advanced                13.8
2                 Advanced                 8.2
3                 Advanced                12.1
4                 Advanced                10.5
...                    ...                 ...
14995             Advanced                 6.0
14996                Basic                 3.6
14997                Basic                 7.3
14998                Basic                 3.6
14999                Basic                13.2

[15000 rows x 33 columns]

In [ ]:
# 3. EDA(Explorative Data Analysis)